
[package]
name = "cocoa-foundation"
description = "Bindings to Cocoa Foundation for macOS"
homepage = "https://github.com/servo/core-foundation-rs"
repository = "https://github.com/servo/core-foundation-rs"
version = "0.1.1"
authors = ["The Servo Project Developers"]
license = "MIT / Apache-2.0"

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"

[dependencies]
block = "0.1"
bitflags = "1.0"
libc = "0.2"
core-foundation = { path = "../core-foundation", version = "0.9" }
core-graphics-types = { path = "../core-graphics-types", version = "0.1" }
foreign-types = "0.3"
# Current `master` of objc
objc = { version = "=0.3.0-alpha.0", package = "objc2" }
objc-encode = "1.1.0"
